#! /bin/sh

sxhkd &

bspc monitor VGA-1 -d I II
bspc monitor HDMI-1 -d III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/startup.sh
picom --config ~/.config/picom/picomrc &
xautolock -locker /bin/v3lock -time 10 &
copyq &

bspc config normal_border_color "#D358F7"
bspc config active_border_color "#2E64FE"
bspc config focused_border_color "#2E64FE"
bspc config presel_border_color "#2E64FE"
bspc config urgent_border_color "#2E64FE"
bspc config presel_feedback_color "#2E64FE"
