#
# ~/.bash_profile
#

#[[ -f ~/.bashrc ]] && . ~/.bashrc

#Path
export PATH=$PATH:/sbin
export LANG=pt_BR.utf8
export CHROME_BIN=/usr/bin/chromium
export PATH=$PATH:/home/$USER/.local/bin

# QT5CT theme
#export QT_STYLE_OVERRIDE=adwaita
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# para o VIM
export TERM=xterm-256color
export COLORTERM=truecolor
export COLORFGBG="15;0"
