#! /bin/sh

sxhkd &

bspc monitor VGA-1 -d I II III IV
bspc monitor HDMI-1 -d V VI VII VIII

#bspc monitor VGA-1 -d 1 2 3 4 5
#bspc monitor HDMI-1 -d 6 7 8 9 0


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/startup.sh
compton &

bspc config normal_border_color "#D358F7"
bspc config active_border_color "#2E64FE"
bspc config focused_border_color "#2E64FE"
bspc config presel_border_color "#2E64FE"
bspc config urgent_border_color "#2E64FE"
bspc config presel_feedback_color "#2E64FE"

